file( GLOB_RECURSE HEADER_LIST FOLLOW_SYMLINKS
      LIST_DIRECTORIES true
      RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
      "../../src/*.h"
)

# separate_arguments(HEADER_LIST)
file(WRITE ${MELPHIG_HEADER} "" )
foreach( HEADER ${HEADER_LIST} )
    file(READ ${HEADER} HEADER_CONTENT)
    file(APPEND ${MELPHIG_HEADER} "${HEADER_CONTENT}")
endforeach()

